### ISSUE TITLE
Suppress password output in build log

### ISSUE THREAD

**Issue by toolforger** [shyiko/servers-maven-extension#7]
Assume you have a `settings.xml` with this content:

``` xml
        <server>
            <id>generic-snapshot-local</id>
            <username>SRNME</username>
            <password>PSSWRD</password>
        </server>
```

Further assume Maven is running at the DEBUG log level.
In that case, you can expect the following to appear in the log output:

`[DEBUG] properties used {..., settings.servers.server.generic-release-local.username=SRNME, ..., settings.servers.server.generic-release-local.password=PSSWRD, ...}`

Now cleartext passwords are NOT what you want to see in a build log: Developers will forget to delete them because they are occupied with whatever other problem they are trying to solve, usually under pressure from a deadline.
(Background: I'm in the Fintech industry. Having logs with passwords is not just a no-no and a slap on the fingers, it's the kind of stuff that can get you fired. As it stands, I cannot use the plugin.)

I can see two alternatives how to deal with this:
a) Somehow suppress the output in the logs. This affects not just the outputs from Maven itselfs but also that of plugins, though one could arguably maintain the position that plugins have no business printing all properties willy-nilly (in my build, that's just `install4j-maven-plugin`, but more may exist).
b) Clearly document the security implications in the documentation of `server-maven-extension`.

I guess (b) is necessary to do first, because doing (a) is going to be pretty difficult, and if Maven internally does not have a way to mark properties as "secret, do not print", (b) will have to stay even if (a) is implemented.

**Comment by shyiko** [comment]
Yeah. I doubt we can do anything about it. Once server.* entries are mixed into the map of properties any plugin (including Maven itself) can access / print them out ([servers-maven-extension](https://github.com/shyiko/servers-maven-extension/blob/master/src/main/java/com/github/shyiko/sme/ServersExtension.java) is not logging them, though). And even if they normally don't do that, they still might under some exceptional conditions (OOM, etc). We could hijack System.out/System.err to zero out server.* values from the log but normally this particular issue can be mitigated with the help of [secret variables](https://docs.travis-ci.com/user/environment-variables/#Encrypting-environment-variables) (most modern CIs support them) (they are automatically stripped away from the log if printed) (e.g. https://github.com/shyiko/ktlint/blob/master/.mvn/settings.xml#L9). 

I'll add a security notice to the README.

**Comment by toolforger** [comment]
Hijacking System.out/.err would limit Maven, somebody might want to add appenders that log elsewhere (UDP, database, whatever - these appenders exist, you just need a plugin to get them into Maven).
It's probably better if Maven handles this  - e.g. it could make use of SLF4J Markers to indicate the presence of secret information in a log message.

Moving secret data to secret variables is a mitigation, but it does not integrate well with the "single source of truth" and build stability. But that's yet another can of worms.
